# Generated by Django 6.0.7 on 2026-07-23 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_name', models.CharField(max_length=255)),
                ('lat', models.FloatField(default=37.7749)),
                ('lng', models.FloatField(default=-122.4194)),
                ('resource_needed', models.CharField(choices=[('water', 'Water'), ('medical', 'Medical'), ('food', 'Food'), ('shelter', 'Shelter'), ('generators', 'Generators'), ('rescue_gear', 'Rescue Gear')], default='water', max_length=50)),
                ('amount_needed', models.IntegerField(default=50)),
                ('people_affected', models.IntegerField(default=100)),
                ('severity', models.IntegerField(default=3)),
                ('urgency_window_hours', models.FloatField(default=4.0)),
                ('urgency_score', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('en_route', 'En Route'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(default='rapid_van', max_length=50)),
                ('capacity', models.IntegerField(default=100)),
                ('max_speed_kmh', models.FloatField(default=50.0)),
                ('depot_name', models.CharField(default='Central Logistics Hub', max_length=255)),
                ('depot_lat', models.FloatField(default=37.7749)),
                ('depot_lng', models.FloatField(default=-122.4194)),
                ('status', models.CharField(choices=[('available', 'Available'), ('en_route', 'En Route'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('driver_name', models.CharField(default='Dispatch Driver', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance_km', models.FloatField(default=0.0)),
                ('total_time_minutes', models.FloatField(default=0.0)),
                ('stops', models.JSONField(default=list)),
                ('driver_instructions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='sites_vehicles.vehicle')),
            ],
        ),
    ]
