# Generated by Django 6.0.7 on 2026-08-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='road_geometry',
            field=models.JSONField(default=list),
        ),
    ]
